import { app, BrowserWindow, ipcMain, net } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

//Paginas de la app
declare const LOGIN_WINDOW_WEBPACK_ENTRY: string;
declare const LOGIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

declare const HOME_WINDOW_WEBPACK_ENTRY: string;
declare const HOME_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(HOME_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
};

ipcMain.handle('nav:toLogin', async () => {
  if (!mainWindow) return;
  console.log('Navigating to login');
    await mainWindow.loadURL(LOGIN_WINDOW_WEBPACK_ENTRY);
    return true;    
});

ipcMain.handle('nav:toHome', async () => {
  if (!mainWindow) return;
  await mainWindow.loadURL(HOME_WINDOW_WEBPACK_ENTRY);
  return true;
});

ipcMain.handle('http:get', async (_e, url: string, options?: any) => {
  const res = await net.fetch(url, { method: 'GET', ...options });
  // Intentar parsear como JSON solo si el Content-Type lo indica
  const contentType = res.headers.get('content-type') || '';
  let body: any;
  try {
    if (contentType.includes('application/json')) {
      body = await res.json();
    } else {
      // Si no es JSON, devolver el texto crudo para que el renderer lo maneje
      body = await res.text();
    }
  } catch (err) {
    // Si el parseo falla, devolver el texto crudo y una nota de error
    try {
      body = await res.text();
    } catch (e) {
      body = null;
    }
  }
  // Convierte cabeceras a objeto simple si quieres retornarlas
  return { status: res.status, ok: res.ok, body, contentType };
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.handle('http:post', async (_e, url: string, body: any, options?: any) => {
  const res = await net.fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(options?.headers || {})
    },
    body: JSON.stringify(body),
    ...options
  });

  const contentType = res.headers.get('content-type') || '';
  let responseBody: any;

  try {
    if (contentType.includes('application/json')) {
      responseBody = await res.json();
    } else {
      responseBody = await res.text();
    }
  } catch (err) {
    try {
      responseBody = await res.text();
    } catch (e) {
      responseBody = null;
    }
  }

  return {
    status: res.status,
    ok: res.ok,
    body: responseBody,
    contentType
  };
});